# Generated by Django 5.1.6 on 2025-08-03 16:05
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Type d'action"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Type d'évènement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de l'évènement"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=200, verbose_name="Lieu de l'évènement"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="images/",
                        verbose_name="Affiche de l'évènement",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(verbose_name="Date et heure de l'évènement"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Prix de l'évènement"
                    ),
                ),
                (
                    "places",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de places"
                    ),
                ),
                (
                    "tickets",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de tickets"
                    ),
                ),
                (
                    "detail",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Description de l'évènement"
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.action",
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.eventtype",
                        verbose_name="Type d'évènement",
                    ),
                ),
            ],
        ),
    ]
