# Generated by Django 5.1.6 on 2025-08-03 16:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Evènement ouvert ?"),
        ),
    ]
