# Generated by Django 5.1.6 on 2025-08-03 18:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={
                "verbose_name": "Types d'actions",
                "verbose_name_plural": "Les actions",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Evènements",
                "verbose_name_plural": "Les évènements",
            },
        ),
        migrations.AlterModelOptions(
            name="eventtype",
            options={
                "verbose_name": "Types d'évènements",
                "verbose_name_plural": "Les types évènements",
            },
        ),
    ]
