# Generated by Django 5.1.6 on 2025-08-27 23:39
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_action_options_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 27, 23, 39, 52, 874176),
                verbose_name="Date  de fin de l'évènement",
            ),
        ),
    ]
