# Generated by Django 5.1.6 on 2025-10-22 09:20
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_event_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 22, 10, 20, 31, 48916),
                verbose_name="Date  de fin de l'évènement",
            ),
        ),
    ]
