# Generated by Django 5.1.6 on 2025-09-25 21:44
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_event_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 25, 21, 44, 25, 204337),
                verbose_name="Date  de fin de l'évènement",
            ),
        ),
    ]
