# Generated by Django 5.1.6 on 2025-09-28 00:51
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_alter_event_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 28, 0, 51, 28, 440224),
                verbose_name="Date  de fin de l'évènement",
            ),
        ),
    ]
