# Generated by Django 5.1.6 on 2025-09-30 01:48
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0016_alter_event_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 30, 1, 48, 21, 818245),
                verbose_name="Date  de fin de l'évènement",
            ),
        ),
    ]
