# Generated by Django 5.1.6 on 2025-11-19 10:36
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_event_event_end_date_local_backup"),
        ("events", "0019_alter_event_event_end_date"),
    ]

    operations = []
