# Generated by Django 5.1.6 on 2025-11-21 16:19
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0020_merge_20251119_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Date  de fin de l'évènement",
            ),
        ),
    ]
