# Generated by Django 5.1.6 on 2025-04-23 23:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=200, verbose_name="Catégorie de l'actualité"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de l'actualite"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="images/",
                        verbose_name="Image de l'actualité",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, verbose_name="Description de l'actualité"
                    ),
                ),
                (
                    "is_up_to_date",
                    models.BooleanField(
                        default=False, verbose_name="Actualité à la une ?"
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True, verbose_name="Vidéo concernant l'actualité"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "slug_uri",
                    models.SlugField(max_length=200, verbose_name="Url converted ?"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Créateur de l'article"
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualité",
                "verbose_name_plural": "Les actualités",
                "ordering": ["-created_at"],
            },
        ),
    ]
