# Generated by Django 5.1.6 on 2025-08-03 14:24
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("actuality", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actuality",
            name="actuality_type",
            field=models.CharField(
                choices=[
                    ("Politique", "Politique"),
                    ("Economie", "Economie"),
                    ("International", "International"),
                    ("Societe", "Societe"),
                    ("Sante", "Sante"),
                    ("Technologie", "Technologie"),
                    ("Environnement", "Environnement"),
                    ("Culture", "Culture"),
                    ("Sports", "Sports"),
                    ("Sciences", "Sciences"),
                    ("Education", "Education"),
                    ("Justice", "Justice"),
                    ("Evenement", "Evenement"),
                    ("Innovation", "Innovation"),
                    ("Podcast", "Podcast"),
                ],
                default="Politique",
                max_length=200,
                verbose_name="Type de l'actualité",
            ),
        ),
        migrations.AlterField(
            model_name="actuality",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Description de l'actualité"
            ),
        ),
    ]
