# Generated by Django 5.1.6 on 2025-09-03 14:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("actuality", "0002_actuality_actuality_type_alter_actuality_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actuality",
            name="actuality_type",
            field=models.CharField(
                choices=[
                    ("Politique", "Politique"),
                    ("Economie", "Economie"),
                    ("International", "International"),
                    ("Societe", "Societe"),
                    ("Sante", "Sante"),
                    ("Technologie", "Technologie"),
                    ("Environnement", "Environnement"),
                    ("Culture", "Culture"),
                    ("Sports", "Sports"),
                    ("Sciences", "Sciences"),
                    ("Education", "Education"),
                    ("Justice", "Justice"),
                    ("Evenement", "Evenement"),
                    ("Innovation", "Innovation"),
                    ("Podcast", "Podcast"),
                    ("Autres", "Autres"),
                ],
                default="Politique",
                max_length=200,
                verbose_name="Type de l'actualité",
            ),
        ),
    ]
