# Generated by Django 5.1.6 on 2025-04-26 23:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description de la vidéo",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier vidéo",
                upload_to="videos/",
                verbose_name="Fichier vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL de la vidéo Youtube ou Vimeo",
                verbose_name="URL de la vidéo",
            ),
        ),
    ]
