# Generated by Django 5.1.6 on 2025-04-27 02:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "miscellaneous",
            "0002_alter_video_description_alter_video_video_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="is_welcome",
            field=models.BooleanField(
                default=False, verbose_name="Carroussel de bienvenue ?"
            ),
        ),
    ]
