# Generated by Django 5.1.6 on 2025-04-27 02:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0003_slider_is_welcome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Titre du carroussel"
            ),
        ),
    ]
