# Generated by Django 5.1.6 on 2025-04-27 03:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0004_alter_slider_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
