# Generated by Django 5.1.6 on 2025-06-07 21:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0005_slider_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Service name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Service email"),
                ),
            ],
        ),
    ]
