# Generated by Django 5.1.6 on 2025-08-03 18:11
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0006_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cookie",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="generalcondition",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="legalnotice",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="personaldata",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
