# Generated by Django 5.1.6 on 2025-08-07 21:24
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0007_alter_about_text_alter_cookie_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Texte"),
        ),
        migrations.AlterField(
            model_name="cookie",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Texte"),
        ),
        migrations.AlterField(
            model_name="generalcondition",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Texte"),
        ),
        migrations.AlterField(
            model_name="legalnotice",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Texte"),
        ),
        migrations.AlterField(
            model_name="personaldata",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Texte"),
        ),
        migrations.AlterField(
            model_name="service",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Adresse mail du service"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom du service"),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Description de la vidéo",
                verbose_name="Description",
            ),
        ),
    ]
