# Generated by Django 5.1.6 on 2025-08-10 11:55
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0008_alter_about_text_alter_cookie_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicity",
            name="pub_file",
            field=models.FileField(
                blank=True, upload_to="images/", verbose_name="Flyer de la publicité"
            ),
        ),
        migrations.AlterField(
            model_name="publicity",
            name="pub_link",
            field=models.URLField(blank=True, verbose_name="Lien de la publicité"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description"),
        ),
    ]
