# Generated by Django 5.1.6 on 2025-08-28 00:33
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "miscellaneous",
            "0009_alter_publicity_pub_file_alter_publicity_pub_link_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=150)),
                ("message", ckeditor.fields.RichTextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, upload_to="uploaded_newsletters/"),
                ),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Les Newsletters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Les abonnés newsletter",
                "ordering": ["email"],
            },
        ),
    ]
