# Generated by Django 5.1.6 on 2025-08-28 00:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0010_newsletter_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="confirmation_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Code de confirmation"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Compte confirmé ?"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="subscribed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de souscription"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="unsubscribed_at",
            field=models.DateTimeField(
                blank=True, verbose_name="Date de désouscription"
            ),
        ),
    ]
