# Generated by Django 5.1.6 on 2025-09-08 14:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0011_alter_subscriber_confirmation_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de prévisualisation / vignette",
                null=True,
                upload_to="videos/thumbnails/",
                verbose_name="Image miniature de la vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="about",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
