# Generated by Django 5.1.6 on 2025-11-21 16:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0014_alter_video_thumbnail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de prévisualisation / vignette",
                null=True,
                upload_to="videos/thumbnails/",
                verbose_name="Image miniature de la vidéo",
            ),
        ),
    ]
