# Generated by Django 5.1.6 on 2025-09-25 21:42
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="Durée en jours"),
                ),
                (
                    "discount_factor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Facteur de réduction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Période publicitaire",
                "verbose_name_plural": "Périodes publicitaires",
                "ordering": ["duration_days"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Multiplier"
                    ),
                ),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Réservé"),
                ),
            ],
            options={
                "verbose_name": "Créneau horaire",
                "verbose_name_plural": "Créneaux horaires",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "price_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix HT"
                    ),
                ),
                (
                    "price_ttc",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix TTC"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.25,
                        max_digits=5,
                        verbose_name="Taux de TVA",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre publicitaire",
                "verbose_name_plural": "Offres publicitaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OfferCaracteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("float", "Float"),
                        ],
                        max_length=20,
                        verbose_name="Type de valeur",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="Clé")),
                ("value", models.CharField(max_length=255, verbose_name="Valeur")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristics",
                        to="offers.offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caractéristique d'offre",
                "verbose_name_plural": "Caractéristiques d'offres",
                "ordering": ["offer", "key"],
            },
        ),
        migrations.CreateModel(
            name="OfferCatergory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_categories_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_categories_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'offre",
                "verbose_name_plural": "Catégories d'offres",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="offers.offercatergory",
            ),
        ),
    ]
