# Generated by Django 5.1.6 on 2025-09-25 22:36
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_rename_offercatergory_offercategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offercaracteristic",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caracteristics",
                to="offers.offer",
                verbose_name="Offre",
            ),
        ),
    ]
