# Generated by Django 5.1.6 on 2025-09-25 22:50
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_timeslot_created_at_timeslot_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="advertisingperiod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advertisingperiod",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="offercaracteristic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offercaracteristic",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="offercategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offercategory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
    ]
