# Generated by Django 5.1.6 on 2025-09-25 23:29
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_remove_offer_created_by_remove_offer_updated_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offercategory",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="offercategory",
            name="updated_by",
        ),
    ]
