# Generated by Django 5.1.6 on 2025-09-27 23:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_remove_offercategory_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisingperiod",
            name="tax_reduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux de reduction",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="tax_augmentation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux d'augmentation",
            ),
        ),
    ]
