# Generated by Django 5.1.6 on 2025-09-27 23:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0007_advertisingperiod_tax_reduction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingperiod",
            name="discount_factor",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Facteur de réduction sur la période. Il sera calculer automatiquement à partir du taux de reduction",
                max_digits=5,
                verbose_name="Facteur de réduction",
            ),
        ),
        migrations.AlterField(
            model_name="advertisingperiod",
            name="tax_reduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Réduction pour la période en %.(ex: 10 = 10% de remise)",
                max_digits=5,
                verbose_name="Taux de reduction",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="multiplier",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Coefficient appliqué au prix. Il Sera calculer automatiquement à partir du taux d'augmentation",
                max_digits=10,
                verbose_name="Multiplier",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="tax_augmentation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Taux d'augmentation en % pour le créneau horaire.(ex: 5 = 5% d'augmentation)",
                max_digits=5,
                verbose_name="Taux d'augmentation",
            ),
        ),
    ]
