# Generated by Django 5.1.6 on 2025-09-28 00:51
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0008_alter_advertisingperiod_discount_factor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("float", "Float"),
                        ],
                        max_length=20,
                        verbose_name="Type de valeur",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristics",
                        to="offers.offercategory",
                        verbose_name="Offre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caractéristique d'offre",
                "verbose_name_plural": "Caractéristiques d'offres",
            },
        ),
        migrations.CreateModel(
            name="OfferCharacteristicValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Valeur")),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="offers.offercharacteristic",
                        verbose_name="Caractéristique",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristic_values",
                        to="offers.offer",
                        verbose_name="Offre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur de caractéristique d'offre",
                "verbose_name_plural": "Valeurs de caractéristiques d'offres",
            },
        ),
        migrations.DeleteModel(
            name="OfferCaracteristic",
        ),
        migrations.AddConstraint(
            model_name="offercharacteristicvalue",
            constraint=models.UniqueConstraint(
                fields=("characteristic", "offer"), name="unique_characteristic_offer"
            ),
        ),
    ]
