# Generated by Django 5.1.6 on 2025-09-28 00:58
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0009_offercharacteristic_offercharacteristicvalue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offercharacteristic",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="offers.offercategory",
                verbose_name="Catégorie",
            ),
        ),
    ]
