# Generated by Django 5.1.6 on 2025-09-30 08:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0011_alter_offer_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offercharacteristic",
            name="category",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("audio", "Audio"),
                    ("video", "Vidéo"),
                    ("popup", "Pop-up"),
                    ("pwa", "PWA"),
                ],
                default="site",
                max_length=20,
                verbose_name="Catégorie",
            ),
        ),
        migrations.DeleteModel(
            name="OfferCategory",
        ),
    ]
