# Generated by Django 5.1.6 on 2025-10-15 23:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0012_alter_offercharacteristic_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("path", models.CharField(max_length=500, verbose_name="Chemin")),
            ],
            options={
                "verbose_name": "Page du site",
                "verbose_name_plural": "Pages du site",
            },
        ),
    ]
