# Generated by Django 5.1.6 on 2025-10-16 00:08
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0014_adplacement"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdPlacementDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("width", models.PositiveIntegerField(verbose_name="Largeur (px)")),
                ("height", models.PositiveIntegerField(verbose_name="Hauteur (px)")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ad_placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="offers.adplacement",
                        verbose_name="Emplacement publicitaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension d'emplacement publicitaire",
                "verbose_name_plural": "Dimensions d'emplacements publicitaires",
                "ordering": ["ad_placement", "name"],
            },
        ),
    ]
