# Generated by Django 5.1.6 on 2025-10-16 00:25
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0015_adplacementdimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="ad_placement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="offers.adplacement",
                verbose_name="Emplacement publicitaire",
            ),
        ),
    ]
