# Generated by Django 5.1.6 on 2025-10-19 12:07
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0016_offer_ad_placement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adplacement",
            name="front_page",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="ad_placement",
        ),
        migrations.CreateModel(
            name="AdvertisingPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Identifiant de référence",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "front_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertising_placements",
                        to="offers.frontpage",
                        verbose_name="Page du site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emplacement publicitaire",
                "verbose_name_plural": "Emplacements publicitaires",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="advertising_placement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="offers.advertisingplacement",
                verbose_name="Associated advertising placement",
            ),
        ),
        migrations.CreateModel(
            name="AdvertisingPlacementDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("width", models.PositiveIntegerField(verbose_name="Largeur (px)")),
                ("height", models.PositiveIntegerField(verbose_name="Hauteur (px)")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "advertising_placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="offers.advertisingplacement",
                        verbose_name="Associated advertising placement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension d'emplacement publicitaire",
                "verbose_name_plural": "Dimensions d'emplacements publicitaires",
                "ordering": ["advertising_placement", "name"],
            },
        ),
        migrations.DeleteModel(
            name="AdPlacementDimension",
        ),
        migrations.DeleteModel(
            name="AdPlacement",
        ),
    ]
