# Generated by Django 5.1.6 on 2025-10-19 12:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0017_remove_adplacement_front_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingplacement",
            name="reference_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Identifiant de référence",
            ),
        ),
    ]
