# Generated by Django 5.1.6 on 2025-12-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du Poste')),
                ('description', models.TextField(verbose_name='Description Complète')),
                ('department', models.CharField(max_length=100, verbose_name='Département')),
                ('type', models.CharField(max_length=50, verbose_name='Type de Contrat')),
                ('location', models.CharField(max_length=100, verbose_name='Localisation')),
                ('experience', models.CharField(max_length=100, verbose_name='Expérience Requise')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='Date de Publication')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('requirements', models.JSONField(default=list, verbose_name='Exigences')),
                ('benefits', models.JSONField(default=list, verbose_name='Avantages')),
            ],
            options={
                'verbose_name': "Offre d'Emploi",
                'verbose_name_plural': "Offres d'Emploi",
                'ordering': ['-posted_date'],
            },
        ),
    ]
