# Generated by Django 5.1.6 on 2025-12-04 11:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'Offre d'Emploi")),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description Complète')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, verbose_name='Exigences')),
                ('benefits', ckeditor.fields.RichTextField(blank=True, verbose_name='Avantages Offerts')),
                ('department', models.CharField(choices=[('Technique', 'Technique'), ('Editorial', 'Editorial'), ('Marketing', 'Marketing'), ('Contenu', 'Contenu')], default='Technique', max_length=200, verbose_name='Departement')),
                ('type', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Freelance', 'Freelance')], default='CDD', max_length=200, verbose_name='Type de contrat')),
                ('location', models.CharField(max_length=100, verbose_name='Localisation')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise à jour')),
                ('slug_uri', models.SlugField(blank=True, max_length=200, verbose_name='Url formatée (facultatif)')),
                ('experience', models.CharField(max_length=100, verbose_name='Expérience Requise')),
                ('posted_date', models.DateField(db_index=True, verbose_name='Date de Publication')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('draft', models.BooleanField(default=False, verbose_name='Brouillon?')),
                ('username', models.CharField(blank=True, max_length=180, verbose_name="Créateur de l'article")),
            ],
            options={
                'verbose_name': "Offre d'Emploi",
                'verbose_name_plural': "Offres d'Emploi",
                'ordering': ['-posted_date'],
            },
        ),
    ]
