# Generated by Django 5.1.6 on 2025-12-05 08:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("carreer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="department",
            field=models.CharField(
                choices=[
                    ("Technique", "Technique"),
                    ("Editorial", "Editorial"),
                    ("Marketing", "Marketing"),
                ],
                default="Technique",
                max_length=200,
                verbose_name="Departement",
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
    ]
