# Generated by Django 5.1.6 on 2025-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='benefits',
            field=models.JSONField(blank=True, default=list, verbose_name='Avantages'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.JSONField(blank=True, default=list, verbose_name='Exigences'),
        ),
    ]
