# Generated by Django 5.1.6 on 2025-12-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreer', '0002_alter_joboffer_benefits_alter_joboffer_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='benefits',
            field=models.TextField(verbose_name='Avantages'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(verbose_name='Exigences'),
        ),
    ]
