# Generated by Django 5.1.6 on 2025-08-31 19:27
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EuroMillionGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nom du joueur"),
                ),
                (
                    "surname",
                    models.CharField(max_length=120, verbose_name="Prenom du joueur"),
                ),
                (
                    "birthday",
                    models.DateField(verbose_name="Date de naissance du joueur"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=120, verbose_name="Numero de téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email du joueur"),
                ),
                ("country", models.CharField(max_length=120, verbose_name="Pays")),
                ("gender", models.CharField(max_length=20, verbose_name="Genre")),
                (
                    "number_de_1_a_50",
                    models.CharField(max_length=120, verbose_name="Numero de 1 à 50"),
                ),
                (
                    "numero_de_1_a_12",
                    models.CharField(max_length=120, verbose_name="Numero de 1 à 12"),
                ),
                (
                    "identity_ID",
                    models.CharField(
                        max_length=120,
                        verbose_name="Numero de pièce d'identité/Passport",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("expired_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tirage Euro million",
                "verbose_name_plural": "Les Tirages Euro millions",
            },
        ),
        migrations.CreateModel(
            name="EuroMillionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Texte Euro million"
                    ),
                ),
            ],
            options={
                "verbose_name": "Texte Euro million",
                "verbose_name_plural": "Textes Euro millions",
            },
        ),
        migrations.CreateModel(
            name="EuroMilllionPatner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nom du partenaire"),
                ),
            ],
            options={
                "verbose_name": "Partenaire Euro million",
                "verbose_name_plural": "Les partenaires Euro millions",
            },
        ),
        migrations.CreateModel(
            name="VideoEuroMillion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        verbose_name="Lien de la video euro million (Youtube)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire Euro million",
                "verbose_name_plural": "Les partenaires Euro millions",
            },
        ),
        migrations.CreateModel(
            name="WinnerTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="Libelle")),
                ("ticket", models.ImageField(upload_to="tickets/")),
                ("sort_date", models.DateField(verbose_name="Date de tirage")),
            ],
            options={
                "verbose_name": "Ticket tiré au sort",
                "verbose_name_plural": "Les tickets tirés au sort",
                "ordering": ["sort_date"],
            },
        ),
    ]
