# Generated by Django 5.1.6 on 2025-08-31 23:34
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="euromilliongame",
            old_name="numero_de_1_a_12",
            new_name="number_1_to_12",
        ),
        migrations.RenameField(
            model_name="euromilliongame",
            old_name="number_de_1_a_50",
            new_name="number_1_to_50",
        ),
    ]
