# Generated by Django 5.1.6 on 2025-09-08 19:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "game",
            "0002_rename_numero_de_1_a_12_euromilliongame_number_1_to_12_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Identifiant du ticket"
                    ),
                ),
                (
                    "player_alias",
                    models.CharField(max_length=120, verbose_name="Alias du joueur"),
                ),
                ("draw_date", models.DateField(verbose_name="Date de tirage")),
                (
                    "main_numbers",
                    models.CharField(
                        max_length=120, verbose_name="Numéros joués (1 à 50)"
                    ),
                ),
                (
                    "lucky_stars",
                    models.CharField(
                        max_length=120, verbose_name="Étoiles jouées (1 à 12)"
                    ),
                ),
                (
                    "ticket",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="player_tickets/",
                        verbose_name="Image du ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket joueur",
                "verbose_name_plural": "Tickets joueurs",
                "ordering": ["-draw_date"],
            },
        ),
        migrations.CreateModel(
            name="ResultatEuromillion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date du tirage")),
                (
                    "main_numbers",
                    models.CharField(
                        max_length=120, verbose_name="Numéros gagnants (1 à 50)"
                    ),
                ),
                (
                    "lucky_stars",
                    models.CharField(
                        max_length=120, verbose_name="Étoiles gagnantes (1 à 12)"
                    ),
                ),
                ("jackpot", models.CharField(max_length=50, verbose_name="Jackpot")),
                (
                    "winners",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de gagnants"
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat EuroMillions",
                "verbose_name_plural": "Résultats EuroMillions",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="videoeuromillion",
            options={
                "verbose_name": "Vidéo Euro million",
                "verbose_name_plural": "Vidéos Euro million",
            },
        ),
    ]
