# Generated by Django 5.1.6 on 2025-08-07 22:54
import uuid

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("site", "Website Carousel"),
                            ("mobile", "Mobile Carousel"),
                            ("popup", "Popup"),
                        ],
                        max_length=20,
                        verbose_name="Type de support",
                    ),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(
                        help_text="Prix in FCFA", verbose_name="Prix unique"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="L'offre publicitaire est toujours active?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Visible en frontend ?",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "audio_durations",
                    models.CharField(
                        blank=True,
                        help_text="Example des durées spots (e.g., 20s, 30s)",
                        max_length=10,
                        verbose_name="Durée de l'audio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre publicitaire",
                "verbose_name_plural": "Les offres publicitaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OfferCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categorie d'offre",
                "verbose_name_plural": "Les catégories d'offre",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AdvertisingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.CharField(max_length=100, null=True)),
                ("end_date", models.CharField(max_length=50, null=True)),
                ("time_slot", models.CharField(max_length=20, null=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertising_options",
                        to="tarifs.advertisingoffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option d'offre",
                "verbose_name_plural": "Les options d'offre",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier",
                "verbose_name_plural": "Les paniers",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tarifs.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="tarifs.advertisingoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre du panier",
                "verbose_name_plural": "Les offres dans le panier",
            },
        ),
        migrations.AddField(
            model_name="advertisingoffer",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="tarifs.offercategory",
                verbose_name="Categorie",
            ),
        ),
        migrations.CreateModel(
            name="OfferOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de l'option"),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Valeur")),
                (
                    "additional_price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra prix de l'option",
                        verbose_name="Prix additionnel de l'option",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="tarifs.advertisingoffer",
                        verbose_name="Offre publicitaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option d'offre",
                "verbose_name_plural": "Les options d'offre",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("email_verified", "Email Verified"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                ("code_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Les commandes",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tarifs.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tarifs.advertisingoffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre du panier",
                "verbose_name_plural": "Les offres dans le panier",
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du placement"),
                ),
                (
                    "available_slots",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Spots diponible"
                    ),
                ),
                (
                    "price_per_slot",
                    models.PositiveIntegerField(verbose_name="Prix par spot"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="tarifs.advertisingoffer",
                        verbose_name="Offre publicitaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Placement",
                "verbose_name_plural": "Les placements",
            },
        ),
    ]
