# Generated by Django 5.1.6 on 2025-08-10 11:05
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tarifs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUserInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enterprise_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom entreprise",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code postal"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pays"
                    ),
                ),
            ],
            options={
                "verbose_name": "Infos d'utilisateur",
                "verbose_name_plural": "Les infos des utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="advertisingoption",
            options={
                "verbose_name": "Option publicitaire",
                "verbose_name_plural": "Les options publicitaires",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Commandes",
                "verbose_name_plural": "Les commandes",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Offre selectionnée par un utilisateur",
                "verbose_name_plural": "Les offres selectionnées par un utilisateur",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advertisingoption",
            name="end_date",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="advertisingoption",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertising_options",
                to="tarifs.advertisingoffer",
                verbose_name="Offre",
            ),
        ),
        migrations.AlterField(
            model_name="advertisingoption",
            name="start_date",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Date de début"
            ),
        ),
        migrations.AlterField(
            model_name="advertisingoption",
            name="time_slot",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Durée du spot"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="tarifs.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tarifs.advertisingoffer",
                verbose_name="Produit",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantité"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AddField(
            model_name="order",
            name="other_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="tarifs.orderuserinformation",
            ),
        ),
    ]
