# Generated by Django 5.1.6 on 2025-04-23 23:15
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de l'emission"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="images/",
                        verbose_name="Image de l'emission",
                    ),
                ),
                ("presentator", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("draft", models.BooleanField(default=False, verbose_name="Brouillon")),
                (
                    "slug_uri",
                    models.SlugField(max_length=200, verbose_name="Url converted ?"),
                ),
            ],
            options={
                "verbose_name": "Emission",
                "verbose_name_plural": "Les émissions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FridayEditorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l'edito"),
                ),
                ("image", models.FileField(upload_to="images/")),
                (
                    "presentator",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom du presentateur"
                    ),
                ),
                (
                    "complete_description",
                    models.TextField(blank=True, verbose_name="Description complete"),
                ),
                (
                    "incomplete_description",
                    models.TextField(blank=True, verbose_name="Description incomplete"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Url du fichier audio"
                    ),
                ),
                (
                    "complete_audio_file",
                    models.FileField(
                        blank=True,
                        upload_to="images/",
                        verbose_name="Fichier audio complet",
                    ),
                ),
                (
                    "incomplete_audio_file",
                    models.FileField(
                        blank=True,
                        upload_to="images/",
                        verbose_name="Fichier audio incomplet",
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("dateline", models.DateField()),
                (
                    "video_link",
                    models.URLField(
                        blank=True, verbose_name="Lien de la video youtube"
                    ),
                ),
                (
                    "slug_uri",
                    models.SlugField(max_length=200, verbose_name="Url converted ?"),
                ),
            ],
            options={
                "verbose_name": "Edito",
                "verbose_name_plural": "Les editos du vendredi",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Poadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du poadcast"),
                ),
                ("image", models.FileField(blank=True, upload_to="poadcast/images/")),
                ("audio", models.FileField(upload_to="poadcast/audio/")),
                ("created_at", models.DateField(auto_now=True)),
                ("audio_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SubEmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de l'emission"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="images/",
                        verbose_name="Image de l'emission",
                    ),
                ),
                ("presentator", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("draft", models.BooleanField(default=False, verbose_name="Brouillon")),
                (
                    "slug_uri",
                    models.SlugField(max_length=200, verbose_name="Url converted ?"),
                ),
                ("video_link", models.URLField(blank=True)),
                (
                    "emission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sousEmission",
                        to="emission.emission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous emission",
                "verbose_name_plural": "Les sous emissions",
                "ordering": ["created_at"],
            },
        ),
    ]
