# Generated by Django 5.1.6 on 2025-08-07 21:24
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("emission", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emission",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="emission",
            name="slug_uri",
            field=models.SlugField(
                max_length=200, verbose_name="Url formatée (facultatif)"
            ),
        ),
        migrations.AlterField(
            model_name="fridayeditorial",
            name="complete_description",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Description complete"
            ),
        ),
        migrations.AlterField(
            model_name="fridayeditorial",
            name="incomplete_description",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Description incomplete"
            ),
        ),
        migrations.AlterField(
            model_name="fridayeditorial",
            name="slug_uri",
            field=models.SlugField(max_length=200, verbose_name="Url formaté ?"),
        ),
        migrations.AlterField(
            model_name="poadcast",
            name="audio",
            field=models.FileField(
                upload_to="poadcast/audio/", verbose_name="Fichier audio mp3"
            ),
        ),
        migrations.AlterField(
            model_name="poadcast",
            name="audio_url",
            field=models.URLField(blank=True, verbose_name="Lien du poadcast"),
        ),
        migrations.AlterField(
            model_name="poadcast",
            name="image",
            field=models.FileField(
                blank=True,
                upload_to="poadcast/images/",
                verbose_name="Pochette du poadcast",
            ),
        ),
        migrations.AlterField(
            model_name="subemission",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="subemission",
            name="slug_uri",
            field=models.SlugField(
                max_length=200, verbose_name="Url formatée (facultatif)"
            ),
        ),
        migrations.AlterField(
            model_name="subemission",
            name="video_link",
            field=models.URLField(blank=True, verbose_name="Lien de la vidéo"),
        ),
    ]
