# Generated by Django 5.1.6 on 2025-08-31 18:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "emission",
            "0002_alter_emission_description_alter_emission_slug_uri_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emission",
            name="slug_uri",
            field=models.SlugField(
                blank=True, max_length=200, verbose_name="Url formatée (facultatif)"
            ),
        ),
        migrations.AlterField(
            model_name="subemission",
            name="slug_uri",
            field=models.SlugField(
                blank=True, max_length=200, verbose_name="Url formatée (facultatif)"
            ),
        ),
    ]
