# Generated by Django 5.1.6 on 2025-09-03 14:55
# Generated by Django 5.1.6 on 2025-09-15 11:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emission", "0003_alter_emission_slug_uri_alter_subemission_slug_uri"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poadcast",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Poadcast",
                "verbose_name_plural": "Les poadcasts",
            },
        ),
    ]
