# Generated by Django 5.1.6 on 2025-09-03 15:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("emission", "0004_alter_poadcast_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subemission",
            name="audio_file",
            field=models.FileField(
                blank=True,
                upload_to="subemission/audio/",
                verbose_name="Fichier audio (upload)",
            ),
        ),
        migrations.AddField(
            model_name="subemission",
            name="video_file",
            field=models.FileField(
                blank=True,
                upload_to="subemission/videos/",
                verbose_name="Fichier vidéo (upload)",
            ),
        ),
    ]
