# Generated by Django 5.1.6 on 2025-09-08 14:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("emission", "0005_subemission_audio_file_subemission_video_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastHoroscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Belier", "Bélier"),
                            ("Taureau", "Taureau"),
                            ("Gemeaux", "Gémeaux"),
                            ("Cancer", "Cancer"),
                            ("Lion", "Lion"),
                            ("Vierge", "Vierge"),
                            ("Balance", "Balance"),
                            ("Scorpion", "Scorpion"),
                            ("Sagittaire", "Sagittaire"),
                            ("Capricorne", "Capricorne"),
                            ("Verseau", "Verseau"),
                            ("Poissons", "Poissons"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "file_audio",
                    models.FileField(
                        upload_to="podcast_horoscope/audio/",
                        verbose_name="Fichier audio mp3",
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Podcast Horoscope",
                "verbose_name_plural": "Podcasts Horoscope",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Poadcast",
        ),
    ]
