# Generated by Django 5.1.6 on 2025-09-08 19:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("emission", "0006_podcasthoroscope_delete_poadcast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcasthoroscope",
            name="file_audio",
            field=models.FileField(
                upload_to="podcast_horoscope/audio/", verbose_name="Fichier audio"
            ),
        ),
    ]
