"""
Django settings for ekila project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

from . import apply_to

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-n!79_xwu_+)^wc0=2p^ui0#cf!&x9rdu_0vsp7s&g92zr=s!x1"

DEBUG = True
DATE_INPUT_FORMATS = ["%d-%m-%Y"]
DATE_FORMAT = "d-m-Y"

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "rest_framework",
    "drf_yasg",
    "drf_spectacular",
    "crispy_forms",
    "corsheaders",
    "ckeditor",
    "actuality",
    "events",
    "miscellaneous",
    "emission",
    "tarifs",
    "game",
    "offers",
    "carreer",
]

CRISPY_TEMPLATE_PACK = "bootstrap4"
X_FRAME_OPTIONS = "SAMEORIGIN"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.cache.FetchFromCacheMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    # "ekila.middleware.MaintenanceModeMiddleware",
]

LANGUAGES = [
    ("fr", "French"),
    ("en", "English"),
]

USE_I18N = True
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

ROOT_URLCONF = "ekila.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ekila.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = 465
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")

EMAIL_EURO_MILLION_MONDE = "emm@mnlvm.fr"
RECEIVER_MAIL_MESSAGE = os.getenv("RECEIVER_MAIL_MESSAGE")
EMAIL_REGEX = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
RECEIVER_MAIL = None
HOSTED_BUTTON_ID = None

MAIL_TO = None


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

MIN_NUMBER = 10000
FRONT_URI = os.getenv("FRONT_URI")
MAX_NUMBER = 99999

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_COOKIE": "refresh_token",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

DURATION_TIME_CODE = 5  # minutes


apply_to(globals())


try:
    from ekila.local_settings import *
except ImportError:
    pass

try:
    from ekila.settings_prod import *
except ImportError:
    pass

JAZZMIN_SETTINGS = {
    "welcome_sign": "MNLV Administration",
    "site_logo": "img/logo.png",
    "site_logo_classes": "img-circle elevation-3",
    "custom_css": "css/custom.css",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "tarifs.cart": "fas fa-shopping-cart",
        "tarifs.cartitem": "fas fa-cart-plus",
        "tarifs.order": "fas fa-file-invoice-dollar",
        "tarifs.orderitem": "fas fa-list-ol",
        "tarifs.placement": "fas fa-map-marker-alt",
        "tarifs.advertisingoffer": "fas fa-bullhorn",
        "tarifs.advertisingoption": "fas fa-cogs",
        "tarifs.offercategory": "fas fa-tags",
        "tarifs.offeroption": "fas fa-sliders-h",
        # actuality
        "actuality.actuality": "fas fa-newspaper",
        # emission
        "emission.emission": "fas fa-microphone",
        "emission.subemission": "fas fa-clone",
        "emission.fridayeditorial": "fas fa-pen-nib",
        "emission.poadcast": "fas fa-podcast",
        # events
        "events.event": "fas fa-calendar-alt",
        "events.eventtype": "fas fa-list",
        "events.action": "fas fa-bolt",
        # game
        "game.euromilliongame": "fas fa-dice",
        "game.euromillionmessage": "fas fa-envelope",
        "game.euromilllionpatner": "fas fa-user-friends",
        "game.videoeuromillion": "fas fa-video",
        # miscellaneous
        "miscellaneous.about": "fas fa-info-circle",
        "miscellaneous.video": "fas fa-film",
        "miscellaneous.slider": "fas fa-images",
        "miscellaneous.publicity": "fas fa-bullhorn",
        "miscellaneous.generalcondition": "fas fa-file-contract",
        "miscellaneous.legalnotice": "fas fa-balance-scale",
        "miscellaneous.personaldata": "fas fa-user-shield",
        "miscellaneous.cookie": "fas fa-cookie-bite",
        "miscellaneous.service": "fas fa-concierge-bell",
        # offers
        "offers.offer": "fas fa-bullhorn",
        "offers.offercategory": "fas fa-tags",
        "offers.timeslot": "fas fa-clock",
        "offers.advertisingperiod": "fas fa-calendar",
        "offers.offercharacteristic": "fas fa-list-ul",
        "offers.offercharacteristicvalue": "fas fa-list",
        "offers.advertisingplacement": "fas fa-map-marker-alt",
        "offers.frontpage": "fas fa-home",
        "offers.advertisingplacementdimension": "fas fa-vector-square",
    },
}
